### ISSUE TITLE
Accessing API via IBMid

### ISSUE THREAD

**Issue by YiannisGkoufas** [IBM/ibmpairs#2]
Was looking in the example notebook here https://github.com/IBM/ibmpairs/blob/master/tutorials/IBM-PAIRS-API-wrapper-tutorial.ipynb 
Wondering if there is a way to access the API if authentication is done with our IBMid

Thanks!

**Comment by cmalbrec** [comment]
Hi @YiannisGkoufas :

Today authentication with IBMid is not supported by the PAIRS Core API which is wrapped by the `paw` Python module. I checked with the corresonding developers: There is plans to have the IBMid authentication feature in the future, but there is no timeline yet. A rough estimate (without warranty) is that perhaps in Q4 this year there will be a solution that serves your request.

As soon as the API supports, I will revisit and check how to incorporate into this repo.

Best,

Conrad

**Comment by YiannisGkoufas** [comment]
Hi Conrad,

thanks for the information. I sent out a request for an account on pairs@us.ibm.com
Is there an estimate about this?

Thanks!

**Comment by cmalbrec** [comment]
Hi @YiannisGkoufas :

You should have received credentials. Pls close the issue if that's the case.

Have a great weekend,

Conrad

**Comment by YiannisGkoufas** [comment]
Hi Conrad, indeed I got them, thanks!
