### ISSUE TITLE
Consider exposing queryStatus in PAW API

### ISSUE THREAD

**Issue by roryodonnell** [IBM/ibmpairs#5]

**Comment by roryodonnell** [comment]
@cmalbrec

**Comment by cmalbrec** [comment]
Hi @roryodonnell :

Could you pls add a description that explains your idea?

Are you after something like this?: https://github.com/IBM/ibmpairs/blob/84fa3ccd9c88666a28132203dd3e28874133a266/ibmpairs/paw.py#L800-L805

Once you created an object from `paw.PAIRSQuery()` you can always explicitly use `self.queryStatus`.

Best,

Conrad

**Comment by roryodonnell** [comment]
Yip - thanks Conrad, able to do the following...
```
pairs_query.submit()
pairs_query.poll_till_finished()
pairs_query.download()
print(pairs_query.queryStatus)
```
