### ISSUE TITLE
Is the Notebook re-run on a regular basis to check it works ?

### ISSUE THREAD

**Issue by kwiatks** [IBM/ibmpairs#7]
I have attempted to run this Notebook within Watson Studio but have reached a step where an error stops further actions to be executed.

Is this Notebook checked on a regular basis ?

# submit PAIRS point query
pointQuery.submit()
pointQuery.poll_till_finished()
pointQuery.download()
pointQuery.create_layers()

[Out]
---------------------------------------------------------------------------
gaierror                                  Traceback (most recent call last)
/opt/conda/envs/Python36/lib/python3.6/site-packages/urllib3/connection.py in _new_conn(self)
    158             conn = connection.create_connection(
--> 159                 (self._dns_host, self.port), self.timeout, **extra_kw)
    160 

/opt/conda/envs/Python36/lib/python3.6/site-packages/urllib3/util/connection.py in create_connection(address, timeout, source_address, socket_options)
     56 
---> 57     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
     58         af, socktype, proto, canonname, sa = res

/opt/conda/envs/Python36/lib/python3.6/socket.py in getaddrinfo(host, port, family, type, proto, flags)
    744     addrlist = []
--> 745     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    746         af, socktype, proto, canonname, sa = res

gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

NewConnectionError                        Traceback (most recent call last)
/opt/conda/envs/Python36/lib/python3.6/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    599                                                   body=body, headers=headers,
--> 600                                                   chunked=chunked)
    601 

/opt/conda/envs/Python36/lib/python3.6/site-packages/urllib3/connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    342         try:
--> 343             self._validate_conn(conn)
    344         except (SocketTimeout, BaseSSLError) as e:

/opt/conda/envs/Python36/lib/python3.6/site-packages/urllib3/connectionpool.py in _validate_conn(self, conn)
    838         if not getattr(conn, 'sock', None):  # AppEngine might not have  `.sock`
--> 839             conn.connect()
    840 

/opt/conda/envs/Python36/lib/python3.6/site-packages/urllib3/connection.py in connect(self)
    300         # Add certificate verification
--> 301         conn = self._new_conn()
    302         hostname = self.host

/opt/conda/envs/Python36/lib/python3.6/site-packages/urllib3/connection.py in _new_conn(self)
    167             raise NewConnectionError(
--> 168                 self, "Failed to establish a new connection: %s" % e)
    169 

NewConnectionError: <urllib3.connection.VerifiedHTTPSConnection object at 0x7fcc290495f8>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
/opt/conda/envs/Python36/lib/python3.6/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    448                     retries=self.max_retries,
--> 449                     timeout=timeout
    450                 )

/opt/conda/envs/Python36/lib/python3.6/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    637             retries = retries.increment(method, url, error=e, _pool=self,
--> 638                                         _stacktrace=sys.exc_info()[2])
    639             retries.sleep()

/opt/conda/envs/Python36/lib/python3.6/site-packages/urllib3/util/retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    397         if new_retry.is_exhausted():
--> 398             raise MaxRetryError(_pool, url, error or ResponseError(cause))
    399 

MaxRetryError: HTTPSConnectionPool(host='pairs.res.ibm', port=443): Max retries exceeded with url: /v2/query (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcc290495f8>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
/opt/conda/envs/Python36/lib/python3.6/site-packages/ibmpairs/paw.py in submit(self)
    961                             auth    = self.auth,
--> 962                             verify  = self.verifySSL,
    963                         )

/opt/conda/envs/Python36/lib/python3.6/site-packages/requests/api.py in post(url, data, json, **kwargs)
    115 
--> 116     return request('post', url, data=data, json=json, **kwargs)
    117 

/opt/conda/envs/Python36/lib/python3.6/site-packages/requests/api.py in request(method, url, **kwargs)
     59     with sessions.Session() as session:
---> 60         return session.request(method=method, url=url, **kwargs)
     61 

/opt/conda/envs/Python36/lib/python3.6/site-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    532         send_kwargs.update(settings)
--> 533         resp = self.send(prep, **send_kwargs)
    534 

/opt/conda/envs/Python36/lib/python3.6/site-packages/requests/sessions.py in send(self, request, **kwargs)
    645         # Send the request
--> 646         r = adapter.send(request, **kwargs)
    647 

/opt/conda/envs/Python36/lib/python3.6/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    515 
--> 516             raise ConnectionError(e, request=request)
    517 

ConnectionError: HTTPSConnectionPool(host='pairs.res.ibm', port=443): Max retries exceeded with url: /v2/query (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcc290495f8>: Failed to establish a new connection: [Errno -2] Name or service not known',))

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
<ipython-input-8-fc18739f15bc> in <module>
      1 # submit PAIRS point query
----> 2 pointQuery.submit()
      3 pointQuery.poll_till_finished()
      4 pointQuery.download()
      5 pointQuery.create_layers()

/opt/conda/envs/Python36/lib/python3.6/site-packages/ibmpairs/paw.py in submit(self)
    964                 except Exception as e:
    965                     raise Exception(
--> 966                         'Sorry, I have trouble to submit your query: {}.'.format(e)
    967                     )
    968                 # check that submission return is proper JSON

Exception: Sorry, I have trouble to submit your query: HTTPSConnectionPool(host='pairs.res.ibm', port=443): Max retries exceeded with url: /v2/query (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcc290495f8>: Failed to establish a new connection: [Errno -2] Name or service not known',)).

**Comment by kwiatks** [comment]
Could the issue be that my account does not allow access to datalayer = 92 ? as specified in https://github.com/IBM/ibmpairs/tree/master/tutorials ?

**Comment by cmalbrec** [comment]
Hi @kwiatks :

I checked the first part of https://github.com/IBM/ibmpairs/blob/9c8045cdb996225e42fc71331157ea8911aef220/tutorials/IBM-PAIRS-API-wrapper-tutorial.ipynb regarding point queries employing a PAIRS user in the same access group as yours. It runs through smoothly.

From the error message you post above, I read
```
Exception: Sorry, I have trouble to submit your query:
HTTPSConnectionPool(host='pairs.res.ibm', port=443):
Max retries exceeded with url: /v2/query (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fcc290495f8>:
Failed to establish a new connection: [Errno -2] Name or service not known',))
```

I would need to see a minimalistic code example that reproduces the error to consult further, but
Is it possible that you modified `PAIRS_SERVER` in https://github.com/IBM/ibmpairs/blob/9c8045cdb996225e42fc71331157ea8911aef220/tutorials/IBM-PAIRS-API-wrapper-tutorial.ipynb?short_path=daeaac1#L221 somehow dropping `.com`? What did you use for `BASE_URI`?

Hope that helps to further investigate.

**Comment by cmalbrec** [comment]
problem resolved by adding `.com` as described above
